Controllers/Carbon2Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Fag_el_Gamous.Models;
using Fag_el_Gamous.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Fag_el_Gamous.Models.Filtering.FilteringCarbon;

namespace Fag_el_Gamous.Controllers
{
    public class Carbon2Controller : Controller
    {
        private readonly waterbuffaloContext _context;

        public Carbon2Controller(waterbuffaloContext context)
        {
            _context = context;
        }

        // GET: Carbon2
        
        public async Task<IActionResult> Index(FilterCarbon filter, int? carbonId, int pageNum = 1)
        {
            //variable of type FilterCarbonLogic
            var filterCarbonLogic = new FilterCarbonLogic(_context);

            //queryModel that is the return from the GetCarbons method
            var queryModel = filterCarbonLogic.GetCarbons(filter);
            
            //creates a list of Burial with Burial IDs (so we can link them in the view)
            ViewBag.MasterBurialList = _context.MasterBurial2
                .Where(c => c.BurialId != null)
                .ToList();

            //creates a list of Carbons with Burial IDs (so we can link them in the view)
            ViewBag.CarbonBurialList = _context.Carbon2
                .Where(c => c.BurialId != null)
                .ToList();

            //Checks to see if user is admin
            var isAdmin = _context.AspNetUsers
                .Where(c => c.UserName == User.Identity.Name);

            foreach(var thing in isAdmin)
            {
                if( thing.isAdmin == true )
                {
                    ViewData["isAdmin"] = true;
                }
            }

            //Checks to see if user is researcher
            var isResearcher = _context.AspNetUsers
                .Where(c => c.UserName == User.Identity.Name);

            foreach (var thing in isResearcher)
            {
                if (thing.isResearcher == true)
                {
                    ViewData["isResearcher"] = true;
                }
            }

            //increased to send more pages to the jQuery Table
            int pageSize = 10000;

            int skip = 0;

            if (pageNum - 1 < 0)
            { skip = 0; }
            else
            {
                skip = (pageNum - 1) * pageSize;
            }

            return View(new PaginationViewModel
            {
                //Carbons = ((IQueryable<Carbon2>)_context.Carbon2.Include(c => c.Burial).ToListAsync()),

            Carbons = (queryModel
                    .Skip(skip)
                    .Take(pageSize)
                    .ToList()),

                PageNumberingInfo = new PageNumberingInfo
                {
                    NumItemsPerPage = pageSize,
                    CurrentPage = pageNum,

                    TotalNumItems = (carbonId == null ? queryModel.Count() :
                        queryModel.Where(x => x.CarbonId == carbonId).Count())
                },

                //used for pagination while filtering
                UrlInfo = Request.QueryString.Value
            });

        }

        // GET: Carbon2/Details/5
        
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var carbon2 = await _context.Carbon2
                .Include(c => c.Burial)
                .FirstOrDefaultAsync(m => m.CarbonId == id);
            if (carbon2 == null)
            {
                return NotFound();
            }

            return View(carbon2);
        }

        // GET: Carbon2/Create
        [Authorize]
        public IActionResult Create()
        {
            //check to see if user is admin
            var isAdmin = _context.AspNetUsers
                .Where(c => c.UserName == User.Identity.Name);

            foreach(var thing in isAdmin)
            {
                if( thing.isAdmin == true )
                {
                    ViewData["isAdmin"] = true;
                }
            }

            //Check to see if user is researcher
            var isResearcher = _context.AspNetUsers
                .Where(c => c.UserName == User.Identity.Name);

            foreach (var thing in isResearcher)
            {
                if (thing.isResearcher == true)
                {
                    ViewData["isResearcher"] = true;
                }
            }


            ViewData["BurialId"] = new SelectList(_context.MasterBurial2, "BurialId", "BurialId");
            return View();
        }

        // POST: Carbon2/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CarbonId,BurialId,LocConcat,RackNum,LocationNs,Ns,LocationEw,Ew,BurialSubplot,Area,BurialNum,RackAlt,TubeNum,Description,SizeMl,Foci,C14Sample2017,Location,Questions,Num,Conventional14cAgeBp,CCalendarDate,Calibrated95PercentCalendarDateMax,Calibrated95PercentCalendarDateMin,Calibrated95PercentCalendarDateSpan,Calibrated95PercentCalendarDateAvg,Category,Notes")] Carbon2 carbon2)
        {
            if (ModelState.IsValid)
            {
                //injects the correctly made LocConcat
                carbon2.LocConcat = ($"{carbon2.Ns} {carbon2.LocationNs} / {carbon2.LocationNs}+10 {carbon2.Ew} {carbon2.LocationEw} / {carbon2.LocationEw}+10 {carbon2.BurialSubplot} #{carbon2.BurialNum}");




                _context.Add(carbon2);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["BurialId"] = new SelectList(_context.MasterBurial2, "BurialId", "BurialId", carbon2.BurialId);
            return View(carbon2);
        }

        // GET: Carbon2/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            //check to see if user is admin
            var isAdmin = _context.AspNetUsers
                .Where(c => c.UserName == User.Identity.Name);

            foreach(var thing in isAdmin)
            {
                if( thing.isAdmin == true )
                {
                    ViewData["isAdmin"] = true;
                }
            }

            //check to see if user is researcher
            var isResearcher = _context.AspNetUsers
                .Where(c => c.UserName == User.Identity.Name);

            foreach (var thing in isResearcher)
            {
                if (thing.isResearcher == true)
                {
                    ViewData["isResearcher"] = true;
                }
            }

            if (id == null)
            {
                return NotFound();
            }

            var carbon2 = await _context.Carbon2.FindAsync(id);
            if (carbon2 == null)
            {
                return NotFound();
            }
            ViewData["BurialId"] = new SelectList(_context.MasterBurial2, "BurialId", "BurialId", carbon2.BurialId);
            return View(carbon2);
        }

        // POST: Carbon2/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CarbonId,BurialId,LocConcat,RackNum,LocationNs,Ns,LocationEw,Ew,BurialSubplot,Area,BurialNum,RackAlt,TubeNum,Description,SizeMl,Foci,C14Sample2017,Location,Questions,Num,Conventional14cAgeBp,CCalendarDate,Calibrated95PercentCalendarDateMax,Calibrated95PercentCalendarDateMin,Calibrated95PercentCalendarDateSpan,Calibrated95PercentCalendarDateAvg,Category,Notes")] Carbon2 carbon2)
        {
            if (id != carbon2.CarbonId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                //injects the correctly made LocConcat
                carbon2.LocConcat = ($"{carbon2.Ns} {carbon2.LocationNs} / {carbon2.LocationNs}+10 {carbon2.Ew} {carbon2.LocationEw} / {carbon2.LocationEw}+10 {carbon2.BurialSubplot} #{carbon2.BurialNum}");


                try
                {
                    _context.Update(carbon2);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!Carbon2Exists(carbon2.CarbonId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BurialId"] = new SelectList(_context.MasterBurial2, "BurialId", "BurialId", carbon2.BurialId);
            return View(carbon2);
        }

        // GET: Carbon2/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            //Check to see if user is admin
            var isAdmin = _context.AspNetUsers
                .Where(c => c.UserName == User.Identity.Name);

            foreach(var thing in isAdmin)
            {
                if( thing.isAdmin == true )
                {
                    ViewData["isAdmin"] = true;
                }
            }

            //Check to see if user is researcher
            var isResearcher = _context.AspNetUsers
                .Where(c => c.UserName == User.Identity.Name);

            foreach (var thing in isResearcher)
            {

Views/Shared/FilterCarbonSummary.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model Fag_el_Gamous.Models.Filtering.FilteringCarbon.FilterCarbon
    <!--partial view for carbons table filter summary-->
    <form method="get" asp-controller="Carbon2" asp-action="Index" asp-route-pagenum="1">
        <label asp-for="BurialSubplot" style="color:black">Burial Subplot</label>
        <select asp-for="BurialSubplot" class="custom-select">
            <option value="">Select an option</option>
            <option value="NW">NW</option>
            <option value="NE">NE</option>
            <option value="SW">SW</option>
            <option value="SE">SE</option>
        </select>
        <br />
        <br />
        <br />
        <label asp-for="RackNum" style="color:black">Rack Number</label>
        <select asp-for="RackNum" class="custom-select">
            <option value="">Select an option</option>
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
            <option value="5">5</option>
            <option value="6">6</option>
            <option value="7">7</option>
            <option value="8">8</option>
            <option value="9">9</option>
            <option value="10">10</option>
            <option value="11">11</option>
            <option value="12">12</option>
            <option value="13">13</option>
            <option value="14">14</option>
            <option value="15">15</option>
            <option value="16">16</option>
            <option value="17">17</option>
            <option value="18">18</option>
            <option value="19">19</option>
            <option value="20">20</option>
            <option value="21">21</option>
            <option value="22">22</option>
            <option value="23">23</option>
            <option value="24">24</option>
            <option value="25">25</option>
            <option value="26">26</option>
            <option value="27">27</option>
            <option value="28">28</option>
            <option value="29">29</option>
            <option value="30">30</option>
            <option value="31">31</option>
            <option value="32">32</option>
            <option value="33">33</option>
            <option value="34">34</option>
            <option value="35">35</option>
            <option value="36">36</option>
            <option value="37">37</option>
            <option value="38">38</option>
            <option value="39">39</option>
            <option value="40">40</option>
        </select>
        <br />
        <button style="float:right" class="btn btn-primary" type="submit">Filter</button>
    </form>

Views/Shared/FilterSampleSummary.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model Fag_el_Gamous.Models.Filtering.FilteringSample.FilterSample
    <!--partial view for samples table filter summary-->
    <form method="get" asp-controller="Samples2" asp-action="Index" asp-route-pagenum="1">
        <label asp-for="Area" style="color:black">Area</label>
        <select asp-for="Area" class="custom-select">
            <option value="">Select an option</option>
            <option value="NW">NW</option>
            <option value="NE">NE</option>
            <option value="SW">SW</option>
            <option value="SE">SE</option>
        </select>
        <br />
        <label asp-for="RackNum" style="color:black">Rack Number</label>
        <select asp-for="RackNum" class="custom-select">
            <option value="">Select an option</option>
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
            <option value="5">5</option>
            <option value="6">6</option>
            <option value="7">7</option>
            <option value="8">8</option>
            <option value="9">9</option>
            <option value="10">10</option>
            <option value="11">11</option>
            <option value="12">12</option>
            <option value="13">13</option>
            <option value="14">14</option>
            <option value="15">15</option>
            <option value="16">16</option>
            <option value="17">17</option>
            <option value="18">18</option>
            <option value="19">19</option>
            <option value="20">20</option>
            <option value="21">21</option>
            <option value="22">22</option>
            <option value="23">23</option>
            <option value="24">24</option>
            <option value="25">25</option>
            <option value="26">26</option>
            <option value="27">27</option>
            <option value="28">28</option>
            <option value="29">29</option>
            <option value="30">30</option>
            <option value="31">31</option>
            <option value="32">32</option>
            <option value="33">33</option>
            <option value="34">34</option>
            <option value="35">35</option>
            <option value="36">36</option>
            <option value="37">37</option>
            <option value="38">38</option>
            <option value="39">39</option>
            <option value="40">40</option>
        </select>
        <br />
        <label asp-for="DateYear" style="color:black">Year</label>
        <select asp-for="DateYear" class="custom-select">
            <option value="">Select an option</option>
            <option value="1988">1988</option>
            <option value="1989">1989</option>
            <option value="1990">1990</option>
            <option value="1991">1991</option>
            <option value="1992">1992</option>
            <option value="1993">1993</option>
            <option value="1994">1994</option>
            <option value="1995">1995</option>
            <option value="1996">1996</option>
            <option value="1997">1997</option>
            <option value="1998">1998</option>
            <option value="1999">1999</option>
            <option value="2000">2000</option>
            <option value="2001">2001</option>
            <option value="2002">2002</option>
            <option value="2003">2003</option>
            <option value="2004">2004</option>
            <option value="2005">2005</option>
            <option value="2006">2006</option>
            <option value="2007">2007</option>
            <option value="2008">2008</option>
            <option value="2009">2009</option>
            <option value="2010">2010</option>
            <option value="2011">2011</option>
            <option value="2012">2012</option>
            <option value="2013">2013</option>
            <option value="2014">2014</option>
            <option value="2015">2015</option>
            <option value="2016">2016</option>
            <option value="2017">2017</option>
            <option value="2018">2018</option>
            <option value="2019">2019</option>
            <option value="2020">2020</option>
            <option value="2021">2021</option>
        </select>
        <br />
        <button style="float:right" class="btn btn-primary" type="submit">Filter</button>
    </form>

Views/Shared/FilterSummary.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model Fag_el_Gamous.Models.Filtering.Filter
<!--partial view for burial table filter summary-->
<form method="get" asp-controller="MasterBurial2" asp-action="Index" asp-route-pagenum="1">
    <label asp-for="BurialSubPlot" style="color:black">Burial Subplot</label>
    <select asp-for="BurialSubPlot" class="custom-select">
        <option value="">Select an option</option>
        <option value="NW">NW</option>
        <option value="NE">NE</option>
        <option value="SW">SW</option>
        <option value="SE">SE</option>
    </select>
    <br />
    <label asp-for="Sex" style="color:black">Sex</label>
    <select asp-for="Sex" class="custom-select">
        <option value="">Select an option</option>
        <option value="M">Male</option>
        <option value="F">Female</option>
    </select>
    <br /><br />
    <br /><br />

    <label asp-for="HairColor" style="color:black">Hair Color</label>
    <select asp-for="HairColor" class="custom-select">
        <option value="">Select an option</option>
        <option value="B">Brown</option>
        <option value="R">Red</option>
        <option value="A">Brown-Red</option>
        <option value="K">Black</option>
        <option value="D">Blonde</option>
        <option value="U">Unknown</option>
    </select>
    <br />
    <label asp-for="HeadDirection" style="color:black">Head Direction</label>
    <select asp-for="HeadDirection" class="custom-select">
        <option value="">Select an option</option>
        <option value="West">West</option>
        <option value="East">East</option>
    </select>
    <br />
    <button style="float:right" class="btn btn-primary" type="submit">Filter</button>
</form>

Views/Shared/_Layout.cshtml
<!--Section3 Group7-->
<!--Devyn Smith-->
<!--Josh Card-->
<!--Kaden Johnson-->
<!--Stephan Peck-->

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link src="~/img/favicon.ico" rel="icon" />
    <link href="~/css/main.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.css" />
    <link rel="stylesheet" href="grid-gallery.css">
    <script src="~/js/site.js"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    @* No worko *@
    @*<meta http-equiv="Content-Security-Policy" content="default-src 'self'">*@



    <!-- Font Awesome Icons -->
    @*<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">*@
    @*<link rel="stylesheet" href="{% static " plugins /fontawesome-free/css/all.min.css" %}">

        <link href="~/loader/css/global.css" rel="stylesheet" />*@


    <!-- CSS Files -->
    <link href="~/css/material-kit.css" rel="stylesheet" />


    <!--<link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />-->
    <link href="~/lib/bootstrap/dist/css/bootstrap-grid.css" rel="stylesheet" />

    <!-- Theme style -->
    <!-- Google Font: Source Sans Pro / Material icons -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!--Data Table css plugin -->
    <link href="~/plugins/DataTables/datatables.min.css" rel="stylesheet" />

</head>

<body class="@ViewBag.pageType sidebar-collapse">
    <nav class="navbar navbar-transparent navbar-color-on-scroll fixed-top navbar-expand-lg" color-on-scroll="100" id="sectionsNav">
        <div class="container">
            <div class="navbar-translate">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                    <!--<img class="img-responsive" width='28%' src="" alt="">-->
                    Home
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="navbar-toggler-icon"></span>
                    <span class="navbar-toggler-icon"></span>
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav ml-auto">




                    @* Header - just extends drop down menu *@

                    @* Buttons of drop down menu with links *@

                    <li class="nav-item">
                        <a asp-controller="MasterBurial2" asp-action="Index" class="nav-link">
                            <i class="material-icons">storage</i>Burial Data
                        </a>
                    </li>
                    <li class="nav-item">
                        <a asp-controller="Samples2" asp-action="Index" class="nav-link">
                            <i class="material-icons">science</i> Biological Samples
                        </a>
                    </li>
                    <li class="nav-item">
                        <a asp-controller="Carbon2" asp-action="Index" class="nav-link">
                            <i class="material-icons">biotech</i> C14 Dating
                        </a>
                    </li>



                    <li class="nav-item" style="font-weight:bold; background-color:white; border-radius:5px">
                        <partial name="_LoginPartial" />
                    </li>


                    <li class="nav-item">
                        <a class="nav-link" asp-controller="AspNetUsers" asp-action="Index">
                            <i class="material-icons">manage_accounts</i> Admin
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>


    <div class="page-header header-filter blur-filter" data-parallax="true" style="background-image: url('@ViewBag.Background');">


        <div class="container" style="text-align:center">
            <div class="row">
                <div class="col-md-8 ml-auto mr-auto">
                    <div class="brand">

                        @* The title from each page will appear here *@
                        <h1>@ViewBag.Title</h1>



                        @* Sub-title *@
                        <h2>@ViewBag.SubTitle</h2>




                    </div>
                </div>
            </div>
        </div>
    </div>

    @* These divs make up the main container with drop shadow *@
    <div class="main main-raised">
        <div class="section section-basic">
            <div class="container">
                @*<vc:navigation-menu/>*@
                @RenderBody()
            </div>
        </div>
    </div>





    <footer class="footer" data-background-color="black">
        <div class="container">


            <div class="copyright float-right" style="font-size: 13px">
                &copy;
                <script>
                    document.write(new Date().getFullrank())
                </script>Group 7 - Section 3
            </div>
        </div>

    </footer>

    <!--   Core JS Files   -->
    <!--<script src="~/js/core/bootstrap-material-design.min.js"></script>
    <script src="~/js/core/jquery.min.js"></script>
    <script src="~/js/core/popper.min.js"></script>
    <script src="~/js/plugins/moment.min.js"></script>
    <script src="~/js/plugins/nouislider.min.js"></script>
    <script src="~/js/plugins/bootstrap-datetimepicker.js"></script>
    <script src="~/js/plugins/jquery.sharrre.js"></script>
    <script src="~/js/plugins/bootstrap-datetimepicker.js"></script>
    <script src="~/js/material-kit.js"></script>-->
    <!--<script src="./assets/js/plugins/moment.min.js"></script>-->
    <!--	Plugin for the Datepicker, full documentation here: https://github.com/Eonasdan/bootstrap-datetimepicker -->
    <!--<script src="./assets/js/plugins/bootstrap-datetimepicker.js" type="text/javascript"></script>-->
    <!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
    <!--<script src="./assets/js/plugins/nouislider.min.js" type="text/javascript"></script>-->
    <!--  Google Maps Plugin    -->
    <!--<script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>-->
    <!-- Control Center for Material Kit: parallax effects, scripts for the example pages etc -->
    <!--<script src="./assets/js/material-kit.min.js?v=2.0.7" type="text/javascript"></script>-->
    <!--   Core JS Files   -->
    <script src="~/plugins/bootstrap/js/core/jquery.min.js"></script>
    <script src="~/plugins/bootstrap/js/core/popper.min.js"></script>
    <script src="~/plugins/bootstrap/js/core/bootstrap-material-design.min.js"></script>

    <script src="~/plugins/bootstrap/js/plugins/moment.min.js"></script>
    <script src="~/plugins/bootstrap/js/plugins/nouislider.min.js"></script>

    <script src="~/plugins/bootstrap/js/material-kit.js"></script>


    <script src="~/js/grader.js"></script>
    <!--added after adding jquery package-->
    <!--Data Table js plugin -->
    <script src="~/plugins/DataTables/datatables.min.js"></script>

    @* Loader *@
    <script src="~/loader/js/loader.js" type="text/javascript"></script>


    @* font awesome *@
    <script src="https://kit.fontawesome.com/b76b70118d.js" crossorigin="anonymous"></script>

    @RenderSection("scripts", required: false)


    <script>


        $(document).ready(function () {
            //init DateTimePickers
            materialKit.initFormExtendedDatetimepickers();

            // Sliders Init
            materialKit.initSliders();
        });




        function scrollToDownload() {
            if ($('.section-download').length != 0) {
                $("html, body").animate({
                    scrollTop: $('.section-download').offset().top
                }, 1000);
            }
        }








    </script>
</body>
</html>